name: Publish Panna SDK to NPM

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node + PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
          registry-url: 'https://registry.npmjs.org/'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build SDK
        run: pnpm --filter @liskhq/panna-sdk build

      - name: Publish SDK ðŸš€
        shell: bash
        run: pnpm publish --filter @liskhq/panna-sdk --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
